In [1]:
### This will be the routine used to take a non-nested GBR regional contributor table and re-assign regions
### Must be using Non-Nested raw data


import pandas as pd
import numpy as np

selectedConstituents = ['Sediment - Fine', 'N_DIN', 'Ametryn', 'Atrazine', 'Diuron', 'Hexazinone', 'Tebuthiuron']

stdGenString = 'LoadToStream (kg)'
stdExpString = 'LoadToRegExport (kg)'
numDaysString = 'Num_Days'
repRegString = 'Rep_Region'
fuString = 'FU'
aream2String = 'AreaM2'
processString = 'Process'
RSDRstring = 'RSDR'
constitString = 'Constituent'

origContribStringForCatch = 'ModelElement'
desiredStringForCatch = 'Catchment'

#rawcontrib = pd.read_csv('P:\projects\RC8_ResultsSets\BU\Regional_Contributor\BU_RC2016_Baseline_RegContributorDataGrid.csv')
#outputFile = 'P:\projects\RC8_ResultsSets\BU\Regional_Contributor\BU_RC2016_Baseline_RegContributorDataGrid_annualised_FilteredWeber_AUSGOV.csv'

rawcontrib = pd.read_csv('P:\projects\RC8_ResultsSets\FI\Regional_Contributor\FI_RC2016_Baseline_RegContributorDataGrid.csv')
outputFile = 'P:\projects\RC8_ResultsSets\FI\Regional_Contributor\FI_RC2016_Baseline_RegContributorDataGrid_annualised_FilteredWeber_AUSGOV.csv'


tempStringForAnnGen = 'AnnLoadToStreamKG'
tempStringForAnnExp = 'AnnLoadToExportKG'


rawcontrib[tempStringForAnnGen] = rawcontrib[stdGenString].div(rawcontrib[numDaysString]).mul(365.25)
rawcontrib[tempStringForAnnExp] = rawcontrib[stdExpString].div(rawcontrib[numDaysString]).mul(365.25)
#rawcontrib['AreaHA'] = rawcontrib['AreaM2'].div(10000)

### Could put alternatives in here to load a different regionalisation from CSV
#altRegs = pd.read_csv('P:\projects\RC7_Results\BU_Exported ReportingRegions.csv')
altRegs = pd.read_csv('P:\projects\RC7_Results\FI_ReportingRegions_NoCurtisIsland.csv')
### Identify the column names we need
catchColName = 'Catchmt'
regColName = 'AUSGMCAS'

In [2]:
rawcontrib.head(5)

,Rep_Region,ModelElement,Constituent,FU,AreaM2,Process,LoadToStream (kg),LoadToRegExport (kg),RSDR,Num_Days,AnnLoadToStreamKG,AnnLoadToExportKG
0,Fitzroy,SC #1608,Atrazine,Water,0.0,Undefined,0.0,0.0,0.604183,10227,0.0,0.0
1,Fitzroy,SC #1608,Atrazine,Water,0.0,Hillslope surface soil,0.0,0.0,0.604183,10227,0.0,0.0
2,Fitzroy,SC #1608,Atrazine,Water,0.0,Hillslope sub-surface soil,0.0,0.0,0.604183,10227,0.0,0.0
3,Fitzroy,SC #1608,Atrazine,Water,0.0,Gully,0.0,0.0,0.604183,10227,0.0,0.0
4,Fitzroy,SC #1608,Atrazine,Water,0.0,Hillslope no source distinction,0.0,0.0,0.604183,10227,0.0,0.0

In [3]:

altRegs.head(15)

     Catchmt RepReg  Terminal_L  Area_km AUSGMCAS
0   SC #1808  Boyne           0        0    Boyne
1   SC #1809  Boyne           0        0    Boyne
2   SC #1846  Boyne           0        0    Boyne
3   SC #1822  Boyne           0        0    Boyne
4   SC #1823  Boyne           0        0    Boyne
5   SC #1807  Boyne           0        0    Boyne
6   SC #1824  Boyne           0        0    Boyne
7   SC #1818  Boyne           0        0    Boyne
8   SC #1821  Boyne           0        0    Boyne
9   SC #1820  Boyne           0        0    Boyne
10  SC #1819  Boyne           0        0    Boyne
11  SC #1806  Boyne           0        0    Boyne
12  SC #1805  Boyne           0        0    Boyne
13  SC #1810  Boyne           0        0    Boyne
14  SC #1826  Boyne           0        0    Boyne

In [4]:
### add alternative regions to raw contributor data

rawcontrib = pd.merge(rawcontrib, altRegs, how='left', left_on=['ModelElement'], right_on=[catchColName]).reset_index()
rawcontrib.head(5)

,index,Rep_Region,ModelElement,Constituent,FU,AreaM2,Process,LoadToStream (kg),LoadToRegExport (kg),RSDR,Num_Days,AnnLoadToStreamKG,AnnLoadToExportKG,Catchmt,RepReg,Terminal_L,Area_km,AUSGMCAS
0,0,Fitzroy,SC #1608,Atrazine,Water,0.0,Undefined,0.0,0.0,0.604183,10227,0.0,0.0,SC #1608,Fitzroy,0,0,Nogoa
1,1,Fitzroy,SC #1608,Atrazine,Water,0.0,Hillslope surface soil,0.0,0.0,0.604183,10227,0.0,0.0,SC #1608,Fitzroy,0,0,Nogoa
2,2,Fitzroy,SC #1608,Atrazine,Water,0.0,Hillslope sub-surface soil,0.0,0.0,0.604183,10227,0.0,0.0,SC #1608,Fitzroy,0,0,Nogoa
3,3,Fitzroy,SC #1608,Atrazine,Water,0.0,Gully,0.0,0.0,0.604183,10227,0.0,0.0,SC #1608,Fitzroy,0,0,Nogoa
4,4,Fitzroy,SC #1608,Atrazine,Water,0.0,Hillslope no source distinction,0.0,0.0,0.604183,10227,0.0,0.0,SC #1608,Fitzroy,0,0,Nogoa

In [5]:
filtered = rawcontrib.loc[rawcontrib[constitString].isin(selectedConstituents)]

#Need to make the new dataframe a standalone object, not a 'slice' of a copy?????
#Otherwise can't drop columns
filtered = filtered.copy()


filtered.head(5)

,index,Rep_Region,ModelElement,Constituent,FU,AreaM2,Process,LoadToStream (kg),LoadToRegExport (kg),RSDR,Num_Days,AnnLoadToStreamKG,AnnLoadToExportKG,Catchmt,RepReg,Terminal_L,Area_km,AUSGMCAS
0,0,Fitzroy,SC #1608,Atrazine,Water,0.0,Undefined,0.0,0.0,0.604183,10227,0.0,0.0,SC #1608,Fitzroy,0,0,Nogoa
1,1,Fitzroy,SC #1608,Atrazine,Water,0.0,Hillslope surface soil,0.0,0.0,0.604183,10227,0.0,0.0,SC #1608,Fitzroy,0,0,Nogoa
2,2,Fitzroy,SC #1608,Atrazine,Water,0.0,Hillslope sub-surface soil,0.0,0.0,0.604183,10227,0.0,0.0,SC #1608,Fitzroy,0,0,Nogoa
3,3,Fitzroy,SC #1608,Atrazine,Water,0.0,Gully,0.0,0.0,0.604183,10227,0.0,0.0,SC #1608,Fitzroy,0,0,Nogoa
4,4,Fitzroy,SC #1608,Atrazine,Water,0.0,Hillslope no source distinction,0.0,0.0,0.604183,10227,0.0,0.0,SC #1608,Fitzroy,0,0,Nogoa

In [6]:
#regLuseSumPlusArea.to_csv('D:/test_out_Burd_AusGov.csv', index=False)
cols = filtered.columns.tolist()
cols

['index',
 'Rep_Region',
 'ModelElement',
 'Constituent',
 'FU',
 'AreaM2',
 'Process',
 'LoadToStream (kg)',
 'LoadToRegExport (kg)',
 'RSDR',
 'Num_Days',
 'AnnLoadToStreamKG',
 'AnnLoadToExportKG',
 'Catchmt',
 'RepReg',
 'Terminal_L',
 'Area_km',
 'AUSGMCAS']

In [7]:
filtered.drop([stdGenString, stdExpString, repRegString], axis=1, inplace=True)
#filtered.drop([stdGenString], axis=1)
#filtered.drop([stdExpString], axis=1)
#filtered.drop([repRegString], axis=1)

filtered.rename(index=str, columns={regColName: repRegString, tempStringForAnnGen: stdGenString, tempStringForAnnExp: stdExpString, origContribStringForCatch: desiredStringForCatch}, inplace=True)

filtered.head(5)



##Remove original data cols, then rename our temp ones. The ',1' tells DROP we're using columns, not rows
#filtered.drop(stdGenString, 1)
#filtered.drop(stdExpString, 1)
#filtered.drop(repRegString, 1)

#filtered.rename(index=str, columns={regColName: repRegString, tempStringForAnnGen: stdGenString, tempStringForAnnExp: stdExpString, origContribStringForCatch: desiredStringForCatch})

#cols = filtered.columns.tolist()
#cols

,index,Catchment,Constituent,FU,AreaM2,Process,RSDR,Num_Days,LoadToStream (kg),LoadToRegExport (kg),Catchmt,RepReg,Terminal_L,Area_km,Rep_Region
0,0,SC #1608,Atrazine,Water,0.0,Undefined,0.604183,10227,0.0,0.0,SC #1608,Fitzroy,0,0,Nogoa
1,1,SC #1608,Atrazine,Water,0.0,Hillslope surface soil,0.604183,10227,0.0,0.0,SC #1608,Fitzroy,0,0,Nogoa
2,2,SC #1608,Atrazine,Water,0.0,Hillslope sub-surface soil,0.604183,10227,0.0,0.0,SC #1608,Fitzroy,0,0,Nogoa
3,3,SC #1608,Atrazine,Water,0.0,Gully,0.604183,10227,0.0,0.0,SC #1608,Fitzroy,0,0,Nogoa
4,4,SC #1608,Atrazine,Water,0.0,Hillslope no source distinction,0.604183,10227,0.0,0.0,SC #1608,Fitzroy,0,0,Nogoa

In [8]:
myCols = [repRegString, desiredStringForCatch, constitString, fuString, processString, stdGenString, stdExpString, RSDRstring, aream2String]

filtered.to_csv(outputFile, columns=myCols, index=False)

print("Done")

Done